### PR TITLE
Update grommet.ts

### PR DESCRIPTION
**Pull request by ShimiSun**
Adding links to Grommet Designers, themes and RTL support.

Hi,

Currently, Grommet is not listed accurately with some missing resources and links, I've updated the framework file to include the missing information.

image

### CODE REVIEW

**Comment by dimitropoulos** [comment]
thanks for the update!! :)

Only one question: the criteria for `RTL` is
> Explicit right-to-Left support for use in apps with languages like Arabic, Hebrew, or Persian.

Can you point me to where on the grommet docs (or github repo) it explicitly says you support RTL?

**Comment by ShimiSun** [comment]
Good question.
You can find the RTL support reference on the Roadmap https://github.com/grommet/grommet/wiki/Roadmap-2020
```
RTL (Right to Left)
By default grommet behavior and handling is left-to-right (LTR). In recent releases, we introduced the functionality that writing and layout displays start from the right of the page and continues to the left. Texts, inputs and Layout components had been adapted to handle RTL. So don't hesitate to send us feedback from your Grommet - RTL experience, we are looking forward to hearing from you and incorporate your feedback. A nice addition will be to have an RTL sample project.
```

**Comment by dimitropoulos** [comment]
Do you think the mention in the roadmap qualifies according to the criteria?  It seems like it doesn't to me but I want to be as diplomatic as possible here.

For example, https://garden.zendesk.com/react-components/buttons/?isRtl has explicit RTL support by means of the `RTL Locale` slider in the left navigation pane.

The utility of this metric is not that RTL is _possible_ with any given framework, but rather that it's well supported out-of-the-box functionality that the framework designers test for and think about when developing.

For example with Dark Mode, probably none of the libraries make it _impossible_ to implement a dark mode by writing very particular CSS.  But the very fact that you _can_ write the CSS to implement a dark mode is a big difference from a library that makes components with a dark mode in mind.  There are all kinds of subtle places (drop shadows, for example) where dark mode vs light mode can be complicated to implement if the library wasn't made with it in mind.

**Comment by ShimiSun** [comment]
@dimitropoulos I agree we need to improve our docs explaining more about RTL, but the bottom line is that we do support it - and I think that is what the criteria should argue.
We have plenty of RTL examples on our storybook code examples, https://storybook.grommet.io/?path=/story/box--rtl
You can type in the storybook search RTL and you'll see RTL coding that can be achieved with grommet.

**Comment by dimitropoulos** [comment]
ahh, great, yes! the example is all I think that's necessary to satisfy the criteria!

:merge-parrot:

**Pull request merged**
